### ISSUE TITLE
Program crashes after loading the replay file. CLOSED due to driver issue.

### ISSUE THREAD

**Issue by r1bnc** [Smertig/among-us-replayer#4]
I'm having a crash when loading the replay file. I am using the windows 10 AME 1903. Not much info to show you, it just crashes after I load a file.

**Comment by Smertig** [comment]
Hello!

Did you get some error message(s) or replayer crashed quietly?
Could you attach `*.aurp` file that you try to open?
What version of replayer do you use? 
Please, try to run replayer from command line (there are may be some useful logs/errors). You can also try to replace any textures from `res/maps` with dummy lightweight images - replayer may crash due to insufficient memory (however it shouldn't).

**Comment by r1bnc** [comment]
Here is a sample aurp (link will expire in 24 hours): https://a.uguu.se/izmqce.aurp
All of my recorded aurp makes the program crash. I ran the replayer in command prompt to see some error message but it does not output anything, it is a silent crash. I tried the latest replayer in the release version as well as the mod.

**Comment by Smertig** [comment]
Sorry for the late answer.

Your `*.aurp` file is absolutely valid, I was able to open it and watch your game. However, I don't know why replayer crashes but I will improve error handling in future updates. Hopefully it would help.

**Comment by r1bnc** [comment]
Thanks, just please improve error handling and messages so, we can debug what the problem was.

**Comment by r1bnc** [comment]
Hi again. I have tried to debug the program with Visual Studio 2012 (I cant get the 2017 or 2019 I dont have disk space for it).
I got the following when I run the replayer:
![bug](https://user-images.githubusercontent.com/8337343/98461206-3a367c80-21a2-11eb-978d-0befc15896c5.png)

This seems to be related to the OpenGL version of my device, I have the Intel GMA 4500MHD which has OpenGL 2.1 IIRC.
What OpenGL version does this program requires? My issue could be related to that.

Thank You

**Comment by Smertig** [comment]
I don't really know, what version of OpenGL replayer requires because it uses SFML as a cross-platform renderer (it should work with OpenGL 2.1).

However, I've built replayer with debug symbols (**.pdb**) to simplify debugging. Download it from [here](https://github.com/Smertig/among-us-replayer/suites/1489952118/artifacts/25897705) (or [here](https://github.com/Smertig/among-us-replayer/actions/runs/359218707)) and try to run under debugger. You should probably see something more informative like call stack and/or function names.

**Comment by r1bnc** [comment]
I'm closing the issue as it appears to be my driver issue that causes the crash. I tried rolling backthe windows driver to Microsoft Basic Adapter and the program worked. But after installing the intel gpu driver it crashes again.

**Comment by r1bnc** [comment]
This program works fine on GNU/Linux using WINE, so I can still view the replays.
Thanks for your efforts and sorry for the issue.

**Comment by Smertig** [comment]
No problem, you are welcome!

By the way, I'm thinking about linux support (just for now the only "windows" feature is the file choose dialog, that will be replaced with ImGui-based one in further versions)
